name: CI

on:
  workflow_dispatch

jobs:
  Release:
   runs-on: ubuntu-latest
    - name :Create release

      with: 
        release_name: ${{github.run_number}}
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - uses: setharu/release-with-changelog@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: setharu/release-with-changelog@v3

      with:

        token: ${{ secrets.GITHUB_TOKEN }}

        exclude: '^Meta'

        commit-template: '- {title} ← {hash}'

        template: |

          ### Changelog

          {commits}

          {range}

          
       
