name: CI

on:





  workflow_dispatch:

    # You can manually trigger a deployment on GitHub.com

    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

    inputs:

      Version:

        description: 'Example: v1.2.3'

        #required: true

jobs:

  Release:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

        with:

          fetch-depth: 50

      - run: git tag ${{ github.event.inputs.Version }}

      - uses: fregante/release-with-changelog@v3

        with:

          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{github.run_number}}
          release_name: Release ${{github.run_number}}

          exclude: true

          template: '{commits}'
