name: Branch_Synchronize

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source Branch to Sync from'
        required: true
      target_branch:
        description: 'Target Branch to Sync with'
        required: true

jobs:
 Synchronizing:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_PAT }}
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.ACTIONS_PAT }}
          source_ref: ${{ github.event.inputs.source_branch }}
          target_branch: ${{ github.event.inputs.target_branch }}
